services:
  postgres:
    container_name: maket_app_postgres_db
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - market_app_net
    restart: unless-stopped

networks:
  market_app_net:
    driver: bridge

volumes:
  postgres:
